#!/bin/bash
#
# polymarket-setup.sh - Preparación para trading en prediction markets
# Guía de setup inicial
#

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🎯 PREDICTION MARKETS - Setup Guide                    ║"
echo "║     Polymarket + Kalshi Preparation                        ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CHECKLIST DE CONFIGURACIÓN"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "1. 🌐 POLYMARKET (https://polymarket.com)"
echo "   ─────────────────────────────────────────"
echo "   [ ] Crear cuenta con email"
echo "   [ ] Verificar identidad (KYC básico)"
echo "   [ ] Depositar USDC (empezar con $10-50)"
echo "   [ ] Descargar app móvil (opcional)"
echo ""
echo "   💡 Estrategia recomendada por agents en Moltbook:"
echo "      - Empezar con $10 (modo aprendizaje)"
echo "      - Focus en eventos políticos/virales"
echo "      - Research con Tavily antes de apostar"
echo "      - Strict risk management"
echo ""

echo "2. 🏛️ KALSHI (https://kalshi.com)"
echo "   ─────────────────────────────────────────"
echo "   [ ] Crear cuenta"
echo "   [ ] Verificación más estricta (US regulated)"
echo "   [ ] Depositar fondos"
echo "   [ ] Explorar mercados financieros/económicos"
echo ""
echo "   💡 Ventaja sobre Polymarket:"
echo "      - Fully regulated US exchange"
echo "      - Mejor para mercados tradicionales"
echo "      - Más confianza para volumen grande"
echo ""

echo "3. 🔧 HERRAMIENTAS TÉCNICAS"
echo "   ─────────────────────────────────────────"
echo "   [ ] API Key de AlphaVantage (gratis):"
echo "       https://www.alphavantage.co/support/#api-key"
echo ""
echo "   [ ] Tavily API Key (para research):"
echo "       https://tavily.com (1,000 llamadas/mes gratis)"
echo ""
echo "   [ ] Instalar finance_monitor.py:"
echo "       python3 ~/clawd/tools/finance-monitor/finance_monitor.py"
echo ""

echo "4. 📊 SISTEMA DE MONITOREO"
echo "   ─────────────────────────────────────────"
echo "   Ya instalado: ~/clawd/tools/finance-monitor/"
echo ""
echo "   Para activar monitoreo automático:"
echo "   python3 ~/clawd/tools/finance-monitor/finance_monitor.py install-cron"
echo ""
echo "   Para ejecutar manualmente:"
echo "   python3 ~/clawd/tools/finance-monitor/finance_monitor.py"
echo ""
echo "   Para ver estado:"
echo "   python3 ~/clawd/tools/finance-monitor/finance_monitor.py status"
echo ""

echo "5. 🧠 ESTRATEGIAS IDENTIFICADAS EN MOLTBOOK"
echo "   ─────────────────────────────────────────"
echo ""
echo "   A. PREDICTION MARKETS (Bajo riesgo)"
echo "      - Eventos políticos con edge en research"
echo "      - Market sentiment analysis"
echo "      - Small bets, track results"
echo ""
echo "   B. QUANT TRADING (Medio riesgo)"
echo "      - Constant API scanning (cada 15 min)"
echo "      - Resolution source divergence"
echo "      - Cross-market arbitrage"
echo ""
echo "   C. COST OPTIMIZATION (Sin riesgo)"
echo "      - Reducir costos de API antes de ganar"
echo "      - Cache responses"
echo "      - Batch requests"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""
echo "🚀 PRÓXIMOS PASOS INMEDIATOS:"
echo ""
echo "1. Abrir cuenta en Polymarket"
echo "2. Depositar $10 USDC"
echo "3. Obtener API key de AlphaVantage"
echo "4. Configurar Tavily (cuando tengas API key)"
echo "5. Empezar con mercados de bajo riesgo"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "⚠️  ADVERTENCIAS:"
echo "   - Nunca apostar más de lo que puedes perder"
echo "   - Empezar pequeño y aprender"
echo "   - Documentar todas las trades"
echo "   - NFA (Not Financial Advice)"
echo ""
echo "📚 Recursos:"
echo "   - ~/clawd/docs/SHIPYARD_FINANCE_REPORT.md"
echo "   - Foro Finance en Moltbook: /f/finance"
echo ""
