#!/bin/bash
#
set -euo pipefail
# test-security-zeroleaks.sh - Setup rápido para probar ZeroLeaks
# Después de leer el análisis, usar este script para evaluar
#

echo "╔════════════════════════════════════════════════════════════╗"
echo "║     🔒 ZeroLeaks - Security Testing Setup                  ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo "📋 CHECKLIST PARA PROBAR ZEROLEAKS"
echo "════════════════════════════════════════════════════════════"
echo ""

echo "1. 📦 INSTALACIÓN"
echo "   ─────────────────────────────────────────"
echo "   # Requiere Bun o Node.js"
echo "   npm install -g zeroleaks"
echo "   # o"
echo "   bun add -g zeroleaks"
echo ""

echo "2. 🔑 CONFIGURACIÓN"
echo "   ─────────────────────────────────────────"
echo "   # 1. Crear cuenta en OpenRouter (gratis):"
echo "   https://openrouter.ai"
echo ""
echo "   # 2. Obtener API key"
echo "   # 3. Agregar a ~/.clawdbot/.env:"
echo "   export OPENROUTER_API_KEY=sk-or-..."
echo ""

echo "3. 🧪 TESTING RÁPIDO"
echo "   ─────────────────────────────────────────"
echo "   # Testear SOUL.md (core de mi identidad)"
echo "   zeroleaks scan --file ~/clawd/SOUL.md --turns 10"
echo ""
echo "   # Testear SECURITY.md (políticas de seguridad)"
echo "   zeroleaks scan --file ~/clawd/docs/SECURITY_ENVIRONMENT_VARIABLES.md --turns 10"
echo ""
echo "   # Testear un skill"
echo "   zeroleaks scan --file ~/clawd/skills/moltbook-api/README.md --turns 5"
echo ""

echo "4. 📊 EVALUACIÓN DE RESULTADOS"
echo "   ─────────────────────────────────────────"
echo "   # Preguntas a responder:"
echo "   - ¿Encontró vulnerabilidades reales?"
echo "   - ¿Son actionable los findings?"
echo "   - ¿Cuántos tokens consumió el scan?"
echo "   - ¿Falsos positivos vs vulnerabilidades reales?"
echo ""

echo "5. 🎯 DECISIÓN"
echo "   ─────────────────────────────────────────"
echo "   Si los resultados son buenos:"
echo "   - [ ] Integrar en workflow de desarrollo"
echo "   - [ ] Testing automático pre-commit"
echo "   - [ ] Reporte semanal de seguridad"
echo ""
echo "   Si los resultados son malos:"
echo "   - [ ] Desinstalar y mantener sistema actual"
echo "   - [ ] Documentar por qué no sirvió"
echo ""

echo "════════════════════════════════════════════════════════════"
echo ""
echo "💰 COSTO ESTIMADO:"
echo "   - Setup: Gratis (open source)"
echo "   - API OpenRouter: ~$5-10/mes para uso regular"
echo "   - Tiempo: 2-3 horas inicial"
echo ""
echo "⚠️  ADVERTENCIAS:"
echo "   - Cada scan consume tokens (tiene costo)"
echo "   - Puede generar falsos positivos"
echo "   - No es sustituto de buenas prácticas de seguridad"
echo ""
echo "📚 DOCUMENTACIÓN:"
echo "   - ~/clawd/docs/ZEROLEAKS_ANALYSIS.md"
echo "   - https://github.com/ZeroLeaks/zeroleaks"
echo ""
echo "🦊 Recomendación: Probar esta semana y evaluar"
echo ""
